# Домашнє завдання 5. Часові ряди та напівструктуровані дані у задачах ML

Pipeline:

1. Setup PostgreSQL (`pgserver`, fallback — `apt-get postgresql`) і завантаження NYC TLC Yellow Taxi (fallback — stub-schema).
2. Daily time-series `t7_hw_taxi_daily` + lag / rolling / expanding features.
3. Синтетичний JSONB event-log `t7_hw_events` (5 типів подій з різними payload).
4. JSONB-оператори `@>`, `?`, `?|`, JSONPath.
5. GIN та expression B-tree індекси + `EXPLAIN (ANALYZE, BUFFERS)`.
6. JSONB vs нормалізована таблиця, MongoDB-pseudocode, Reflection.

Notebook розрахований на **Restart & Run All**: усі об'єкти створюються через `DROP ... IF EXISTS` / `CREATE OR REPLACE`,
а залежний view видаляється до перестворення базової таблиці.

## Завдання 1. Setup і завантаження даних

Основний шлях — `pgserver`, як у завданні. Для частини версій Python у Colab `pgserver` може не мати збірки, тому, якщо його
не вдається імпортувати, клітинка піднімає системний PostgreSQL через `apt-get`. Змінна середовища `HW7_DB_URI` дозволяє
підключитися до вже запущеного сервера. Далі notebook працює лише з `engine`.

In [1]:
import os

if not os.environ.get('HW7_DB_URI'):
    %pip install -q pgserver
%pip install -q psycopg2-binary sqlalchemy pandas pyarrow requests

Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import subprocess
from urllib.request import urlretrieve

import pandas as pd
from sqlalchemy import create_engine, text

pd.set_option('display.max_columns', 20)
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.width', 200)

if os.environ.get('HW7_DB_URI'):
    db_uri = os.environ['HW7_DB_URI']
    print('PostgreSQL backend: external server from HW7_DB_URI')
else:
    try:
        import pgserver

        pg = pgserver.get_server('/tmp/hw7_pg', cleanup_mode='stop')
        db_uri = pg.get_uri()
        print('PostgreSQL backend: pgserver')
    except Exception as exc:
        # Fallback для Colab: системний PostgreSQL з apt
        print(f'pgserver недоступний ({exc!r}) → apt-get postgresql')
        for cmd in [
            'apt-get update -qq',
            'apt-get install -y -qq postgresql postgresql-contrib > /dev/null',
            'service postgresql start',
            "sudo -u postgres psql -q -c \"ALTER USER postgres WITH PASSWORD 'postgres';\"",
        ]:
            subprocess.run(cmd, shell=True, check=True)
        db_uri = 'postgresql://postgres:postgres@127.0.0.1:5432/postgres'
        print('PostgreSQL backend: apt-get postgresql')

# SQLAlchemy 2.1+ за замовчуванням обирає psycopg (v3) — явно вказуємо встановлений psycopg2.
# Сесійна таймзона UTC: TIMESTAMPTZ у output-ах не залежить від локальних налаштувань машини / Colab.
engine = create_engine(
    db_uri.replace('postgresql://', 'postgresql+psycopg2://', 1),
    connect_args={'options': '-c TimeZone=UTC'},
    future=True,
)

with engine.connect() as conn:
    print(conn.execute(text('SELECT version()')).scalar_one())

PostgreSQL backend: pgserver
PostgreSQL 16.2 on aarch64-apple-darwin23.5.0, compiled by Apple clang version 15.0.0 (clang-1500.0.40.1), 64-bit

Допоміжні функції. `run()` виконує SQL-скрипт (можна кілька statements) через psycopg2 і повертає
результат останнього statement як `DataFrame`. `explain()` друкує план запиту як текст, щоб output
`EXPLAIN (ANALYZE, BUFFERS)` зберігався в notebook у читабельному вигляді.

In [3]:
def run(sql_text):
    raw = engine.raw_connection()
    try:
        with raw.cursor() as cur:
            cur.execute(sql_text)
            result = (
                pd.DataFrame(cur.fetchall(), columns=[d.name for d in cur.description])
                if cur.description else None
            )
        raw.commit()
    finally:
        raw.close()
    return result


def explain(sql_text):
    plan = run(sql_text)
    print('\n'.join(plan.iloc[:, 0]))

### Варіант A. NYC TLC Yellow Taxi (з fallback на Варіант B)

**Чому не просто `head(500_000)` з одного місяця.** Parquet-файл TLC приблизно відсортований за часом:
перші 500 000 рядків `yellow_tripdata_2024-03` покривають лише 1–6 березня. На такій історії
`trips_lag_30d` завжди `NULL`, і фінальний feature view був би порожнім. Тому:

* беремо дві місячні партиції (лютий і березень 2024) — 60 днів, як і в stub-схемі;
* з кожного місяця беремо **відтворювану рівномірну вибірку** `sample(250_000, random_state=42)` → разом 500 000 рядків;
* відкидаємо поїздки, у яких pickup не потрапляє у свій місяць (у файлах трапляються записи з 2002, 2009 тощо).

Якщо завантаження не вдалося (немає мережі), notebook автоматично переходить на stub-schema (`USE_STUB = True`).

In [4]:
DATA_DIR = '/content' if os.path.isdir('/content') else 'data'
os.makedirs(DATA_DIR, exist_ok=True)

MONTHS = ['2024-02', '2024-03']
ROWS_PER_MONTH = 250_000
BASE_URL = 'https://d37ci6vzurychx.cloudfront.net/trip-data/'

columns = [
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime',
    'PULocationID',
    'DOLocationID',
    'trip_distance',
    'fare_amount',
    'passenger_count',
]

USE_STUB = False
frames = []
try:
    for month in MONTHS:
        parquet_path = os.path.join(DATA_DIR, f'yellow_tripdata_{month}.parquet')
        if not os.path.exists(parquet_path):
            urlretrieve(f'{BASE_URL}yellow_tripdata_{month}.parquet', parquet_path)

        month_df = pd.read_parquet(parquet_path, columns=columns)
        month_start = pd.Timestamp(f'{month}-01')
        month_end = month_start + pd.offsets.MonthBegin(1)
        month_df = month_df[
            (month_df['tpep_pickup_datetime'] >= month_start)
            & (month_df['tpep_pickup_datetime'] < month_end)
        ]
        frames.append(month_df.sample(n=ROWS_PER_MONTH, random_state=42))
except Exception as exc:
    print(f'TLC download/read failed, falling back to stub-schema: {exc!r}')
    USE_STUB = True

if not USE_STUB:
    df = pd.concat(frames, ignore_index=True)

    # Basic cleaning before loading to PostgreSQL
    df = df[(df['fare_amount'] > 0) & (df['fare_amount'] < 500)]
    df = df[(df['trip_distance'] > 0) & (df['trip_distance'] < 100)]
    df = df[df['PULocationID'].notna()]

    df.to_sql(
        'nyc_taxi_raw',
        engine,
        if_exists='replace',
        index=False,
        chunksize=10_000,
    )

print('USE_STUB =', USE_STUB)
run('SELECT COUNT(*) AS n_rows FROM nyc_taxi_raw') if not USE_STUB else None

USE_STUB = False

   n_rows
0  481243

In [5]:
run('''
SELECT
    MIN(tpep_pickup_datetime) AS min_pickup,
    MAX(tpep_pickup_datetime) AS max_pickup,
    pg_typeof(MIN(tpep_pickup_datetime)) AS raw_type,
    COUNT(DISTINCT "PULocationID") AS n_zones
FROM nyc_taxi_raw
''') if not USE_STUB else None

           min_pickup          max_pickup                     raw_type  n_zones
0 2024-02-01 00:00:16 2024-03-31 23:59:49  timestamp without time zone      240

### Daily aggregation `t7_hw_taxi_daily` з calendar spine

Відмінність від базового шаблону: агрегат будується поверх **calendar spine** (`generate_series` днів × зони).
Без spine для зон, де в якийсь день не було поїздок, рядок просто відсутній, і `LAG(trip_count, 7)`
повертав би значення не «7 днів тому», а «7 *рядків* тому» — тиха off-by-one помилка в ML-ознаці.
Зі spine кожна зона має рівно один рядок на кожен день, порожні дні мають `trip_count = 0`, `total_distance = 0`,
`avg_fare = NULL` (середньої ціни для нуля поїздок не існує).

`ts_day` має тип `DATE`: день рахується за **локальним NYC днем**, бо raw `tpep_pickup_datetime` — це NYC wall-clock час.

Перед `DROP TABLE` видаляємо залежний view `v_t7_hw_taxi_features`, інакше повторний Run All впаде
з `cannot drop table ... because other objects depend on it` (pgserver зберігає дані в `/tmp/hw7_pg` між запусками).

In [6]:
TAXI_DAILY_REAL_SQL = """
DROP VIEW IF EXISTS v_t7_hw_taxi_features;
DROP TABLE IF EXISTS t7_hw_taxi_daily;

CREATE TABLE t7_hw_taxi_daily AS
WITH trips AS (
    SELECT
        "PULocationID"::INTEGER AS pickup_zone_id,
        tpep_pickup_datetime::TIMESTAMP::DATE AS ts_day,
        fare_amount,
        trip_distance
    FROM nyc_taxi_raw
    WHERE fare_amount > 0
      AND fare_amount < 500
      AND trip_distance > 0
      AND trip_distance < 100
      AND "PULocationID" IS NOT NULL
),
daily AS (
    SELECT
        pickup_zone_id,
        ts_day,
        COUNT(*)::INTEGER AS trip_count,
        AVG(fare_amount)::NUMERIC(10, 2) AS avg_fare,
        SUM(trip_distance)::NUMERIC(12, 2) AS total_distance
    FROM trips
    GROUP BY pickup_zone_id, ts_day
),
calendar AS (
    SELECT d::DATE AS ts_day
    FROM generate_series(
        (SELECT MIN(ts_day) FROM trips)::TIMESTAMP,
        (SELECT MAX(ts_day) FROM trips)::TIMESTAMP,
        INTERVAL '1 day'
    ) AS d
),
zones AS (
    SELECT DISTINCT pickup_zone_id FROM trips
)
SELECT
    z.pickup_zone_id,
    c.ts_day,
    COALESCE(d.trip_count, 0)::INTEGER AS trip_count,
    d.avg_fare,
    COALESCE(d.total_distance, 0)::NUMERIC(12, 2) AS total_distance
FROM zones AS z
CROSS JOIN calendar AS c
LEFT JOIN daily AS d
       ON d.pickup_zone_id = z.pickup_zone_id
      AND d.ts_day = c.ts_day;

ALTER TABLE t7_hw_taxi_daily
    ADD PRIMARY KEY (pickup_zone_id, ts_day);

ANALYZE t7_hw_taxi_daily;
"""

TAXI_DAILY_STUB_SQL = """
DROP VIEW IF EXISTS v_t7_hw_taxi_features;
DROP TABLE IF EXISTS t7_hw_taxi_daily;

CREATE TABLE t7_hw_taxi_daily (
    pickup_zone_id  INTEGER NOT NULL,
    ts_day          DATE    NOT NULL,
    trip_count      INTEGER NOT NULL CHECK (trip_count >= 0),
    avg_fare        NUMERIC(10, 2) NOT NULL CHECK (avg_fare >= 0),
    total_distance  NUMERIC(12, 2) NOT NULL CHECK (total_distance >= 0),
    PRIMARY KEY (pickup_zone_id, ts_day)
);

INSERT INTO t7_hw_taxi_daily (
    pickup_zone_id,
    ts_day,
    trip_count,
    avg_fare,
    total_distance
)
SELECT
    z.zone_id,
    DATE '2024-03-31' - (59 - n) AS ts_day,
    500 + (n * 7) + z.zone_id * 50 + (n % 5) * 30 AS trip_count,
    (12.5 + z.zone_id * 0.7 + (n % 4) * 0.4)::NUMERIC(10, 2) AS avg_fare,
    (1500 + n * 25 + z.zone_id * 120)::NUMERIC(12, 2) AS total_distance
FROM generate_series(0, 59) AS n
CROSS JOIN (VALUES (1), (2), (3), (4), (5)) AS z(zone_id);

ANALYZE t7_hw_taxi_daily;
"""

run(TAXI_DAILY_STUB_SQL if USE_STUB else TAXI_DAILY_REAL_SQL)

run("""
SELECT
    COUNT(*) AS n_rows,
    COUNT(DISTINCT pickup_zone_id) AS n_zones,
    COUNT(DISTINCT ts_day) AS n_days,
    MIN(ts_day) AS min_day,
    MAX(ts_day) AS max_day,
    SUM(trip_count) AS total_trips,
    COUNT(*) FILTER (WHERE trip_count = 0) AS zero_trip_days
FROM t7_hw_taxi_daily
""")

   n_rows  n_zones  n_days     min_day     max_day  total_trips  zero_trip_days
0   14400      240      60  2024-02-01  2024-03-31       481243            5914

In [7]:
run("""
SELECT pickup_zone_id, COUNT(*) AS n_days, SUM(trip_count) AS trips
FROM t7_hw_taxi_daily
GROUP BY pickup_zone_id
ORDER BY pickup_zone_id
LIMIT 10
""")

   pickup_zone_id  n_days  trips
0               1      60      6
1               3      60     14
2               4      60    835
3               6      60      3
4               7      60    262
5               9      60     10
6              10      60    154
7              11      60     11
8              12      60    155
9              13      60   2841

Для ML-ознак беремо зони з достатнім обсягом: у малих зонах (кілька поїздок на місяць) daily-ряд майже весь
нульовий, а `avg_fare` визначений лише в окремі дні. Топ-зони за кількістю поїздок:

In [8]:
run("""
SELECT pickup_zone_id, SUM(trip_count) AS trips, COUNT(*) FILTER (WHERE trip_count = 0) AS zero_days
FROM t7_hw_taxi_daily
GROUP BY pickup_zone_id
ORDER BY trips DESC
LIMIT 10
""")

   pickup_zone_id  trips  zero_days
0             161  22984          0
1             237  22392          0
2             236  20784          0
3             132  20461          0
4             162  16920          0
5             230  16599          0
6             142  15899          0
7             186  15712          0
8             138  14322          0
9             239  14302          0

### Production-style typed таблиця з `TIMESTAMPTZ`

Raw `TIMESTAMP` (без зони) інтерпретується як NYC wall-clock час через `AT TIME ZONE 'America/New_York'`
і перетворюється на абсолютний момент `TIMESTAMPTZ`. Зверніть увагу на 10 березня 2024 — перехід на літній час (DST):
локальна година 02:00–03:00 не існує, і offset змінюється з `-05` на `-04`.

In [9]:
if not USE_STUB:
    run("""
    DROP TABLE IF EXISTS t7_hw_taxi_trips_typed;

    CREATE TABLE t7_hw_taxi_trips_typed AS
    SELECT
        "PULocationID"::INTEGER AS pickup_zone_id,
        "DOLocationID"::INTEGER AS dropoff_zone_id,
        (tpep_pickup_datetime::TIMESTAMP AT TIME ZONE 'America/New_York') AS pickup_at,
        (tpep_dropoff_datetime::TIMESTAMP AT TIME ZONE 'America/New_York') AS dropoff_at,
        trip_distance::NUMERIC(10, 2) AS trip_distance,
        fare_amount::NUMERIC(10, 2) AS fare_amount,
        passenger_count::INTEGER AS passenger_count
    FROM nyc_taxi_raw
    WHERE fare_amount > 0
      AND fare_amount < 500
      AND trip_distance > 0
      AND trip_distance < 100;
    """)

    display(run("""
    SELECT pickup_at, pg_typeof(pickup_at) AS pickup_type
    FROM t7_hw_taxi_trips_typed
    LIMIT 5
    """))

    display(run("""
    (
        SELECT
            to_char(pickup_at AT TIME ZONE 'America/New_York', 'YYYY-MM-DD HH24:MI:SS') AS nyc_local,
            ((pickup_at AT TIME ZONE 'America/New_York') - (pickup_at AT TIME ZONE 'UTC'))::TEXT AS nyc_utc_offset,
            to_char(pickup_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') AS utc,
            pg_typeof(pickup_at) AS pickup_type
        FROM t7_hw_taxi_trips_typed
        WHERE pickup_at >= TIMESTAMPTZ '2024-03-10 01:55:00 America/New_York'
        ORDER BY pickup_at
        LIMIT 3
    )
    UNION ALL
    (
        SELECT
            to_char(pickup_at AT TIME ZONE 'America/New_York', 'YYYY-MM-DD HH24:MI:SS'),
            ((pickup_at AT TIME ZONE 'America/New_York') - (pickup_at AT TIME ZONE 'UTC'))::TEXT,
            to_char(pickup_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            pg_typeof(pickup_at)
        FROM t7_hw_taxi_trips_typed
        WHERE pickup_at >= TIMESTAMPTZ '2024-03-10 03:00:00 America/New_York'
        ORDER BY pickup_at
        LIMIT 3
    )
    """))

                  pickup_at               pickup_type
0 2024-03-28 13:24:12+00:00  timestamp with time zone
1 2024-03-22 21:10:07+00:00  timestamp with time zone
2 2024-03-10 17:37:24+00:00  timestamp with time zone
3 2024-03-09 07:02:35+00:00  timestamp with time zone
4 2024-03-26 10:58:32+00:00  timestamp with time zone

             nyc_local nyc_utc_offset                  utc               pickup_type
0  2024-03-10 01:55:02      -05:00:00  2024-03-10 06:55:02  timestamp with time zone
1  2024-03-10 01:55:11      -05:00:00  2024-03-10 06:55:11  timestamp with time zone
2  2024-03-10 01:55:17      -05:00:00  2024-03-10 06:55:17  timestamp with time zone
3  2024-03-10 03:00:06      -04:00:00  2024-03-10 07:00:06  timestamp with time zone
4  2024-03-10 03:00:06      -04:00:00  2024-03-10 07:00:06  timestamp with time zone
5  2024-03-10 03:00:07      -04:00:00  2024-03-10 07:00:07  timestamp with time zone

## Завдання 2. Time-series ML features

Усі ознаки рахуються з `PARTITION BY pickup_zone_id`. Завдяки calendar spine `ROWS`-based `LAG(n)` дорівнює рівно
`n` календарним дням, а `RANGE ... INTERVAL` frames і так рахують календарні дні.
Для прикладів показуємо найбільшу зону (`pickup_zone_id = 132`, JFK, якщо дані real) — у stub-режимі зону 1.

In [10]:
DEMO_ZONE = 1 if USE_STUB else 132

### Feature 1. Lag features: lag-1d, lag-7d, lag-30d

In [11]:
run(f"""
SELECT *
FROM (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        LAG(trip_count, 1)  OVER w AS trips_lag_1d,
        LAG(trip_count, 7)  OVER w AS trips_lag_7d,
        LAG(trip_count, 30) OVER w AS trips_lag_30d
    FROM t7_hw_taxi_daily
    WINDOW w AS (
        PARTITION BY pickup_zone_id
        ORDER BY ts_day
    )
) AS f
WHERE pickup_zone_id = {DEMO_ZONE}
ORDER BY pickup_zone_id, ts_day
LIMIT 20
""")

    pickup_zone_id      ts_day  trip_count  trips_lag_1d  trips_lag_7d trips_lag_30d
0              132  2024-02-01         312           NaN           NaN          None
1              132  2024-02-02         294         312.0           NaN          None
2              132  2024-02-03         267         294.0           NaN          None
3              132  2024-02-04         412         267.0           NaN          None
4              132  2024-02-05         352         412.0           NaN          None
5              132  2024-02-06         322         352.0           NaN          None
6              132  2024-02-07         279         322.0           NaN          None
7              132  2024-02-08         326         279.0         312.0          None
8              132  2024-02-09         331         326.0         294.0          None
9              132  2024-02-10         294         331.0         267.0          None
10             132  2024-02-11         376         294.0         412.0          None
11             132  2024-02-12         368         376.0         352.0          None
12             132  2024-02-13         262         368.0         322.0          None
13             132  2024-02-14         304         262.0         279.0          None
14             132  2024-02-15         298         304.0         326.0          None
15             132  2024-02-16         343         298.0         331.0          None
16             132  2024-02-17         310         343.0         294.0          None
17             132  2024-02-18         343         310.0         376.0          None
18             132  2024-02-19         460         343.0         368.0          None
19             132  2024-02-20         386         460.0         262.0          None

На перших 30 днях кожної зони `trips_lag_30d` = `NULL`. Фільтр по зоні застосовано **ззовні** підзапиту:
якщо поставити `WHERE` всередині, window function рахувалась би вже після фільтра (тут результат той самий,
бо фільтр по ключу партиції, але для фільтрів по даті це змінило б lag-и).

### Feature 2. Rolling 7-day average fare

`RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW` = 7 календарних днів включно з поточним.
`AVG` ігнорує `NULL`, тому `fare_days_in_window` рахує лише дні з поїздками, а `days_in_window` — усі дні frame
(на початку ряду він менший за 7 — warm-up).

In [12]:
run(f"""
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    AVG(avg_fare)   OVER w7 AS rolling_avg_fare_7d,
    COUNT(*)        OVER w7 AS days_in_window,
    COUNT(avg_fare) OVER w7 AS fare_days_in_window
FROM t7_hw_taxi_daily
WHERE pickup_zone_id = {DEMO_ZONE}
WINDOW w7 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
""")

    pickup_zone_id      ts_day avg_fare  rolling_avg_fare_7d  days_in_window  fare_days_in_window
0              132  2024-02-01    62.03  62.0300000000000000               1                    1
1              132  2024-02-02    65.58  63.8050000000000000               2                    2
2              132  2024-02-03    61.30  62.9700000000000000               3                    3
3              132  2024-02-04    64.15  63.2650000000000000               4                    4
4              132  2024-02-05    65.96  63.8040000000000000               5                    5
5              132  2024-02-06    64.37  63.8983333333333333               6                    6
6              132  2024-02-07    63.81  63.8857142857142857               7                    7
7              132  2024-02-08    63.11  64.0400000000000000               7                    7
8              132  2024-02-09    63.21  63.7014285714285714               7                    7
9              132  2024-02-10    63.32  63.9900000000000000               7                    7
10             132  2024-02-11    62.62  63.7714285714285714               7                    7
11             132  2024-02-12    61.00  63.0628571428571429               7                    7
12             132  2024-02-13    59.09  62.3085714285714286               7                    7
13             132  2024-02-14    64.82  62.4528571428571429               7                    7
14             132  2024-02-15    65.37  62.7757142857142857               7                    7
15             132  2024-02-16    66.15  63.1957142857142857               7                    7
16             132  2024-02-17    65.16  63.4585714285714286               7                    7
17             132  2024-02-18    60.67  63.1800000000000000               7                    7
18             132  2024-02-19    62.76  63.4314285714285714               7                    7
19             132  2024-02-20    60.85  63.6828571428571429               7                    7

**ROWS vs RANGE.** `ROWS BETWEEN 6 PRECEDING` рахує 6 *рядків*, `RANGE BETWEEN INTERVAL '6 days' PRECEDING` — 6 *календарних днів*.
На ряді без пропусків вони збігаються; на ряді з пропусками — ні. Перевірка на сирому агрегаті без spine
(у малих зонах є дні без поїздок):

In [13]:
run("""
WITH sparse AS (
    -- той самий daily-агрегат, але БЕЗ calendar spine: дні без поїздок відсутні
    SELECT pickup_zone_id, ts_day, avg_fare
    FROM t7_hw_taxi_daily
    WHERE trip_count > 0
),
cmp AS (
    SELECT
        pickup_zone_id,
        ts_day,
        COUNT(*) OVER (PARTITION BY pickup_zone_id ORDER BY ts_day
                       ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rows_frame_size,
        MIN(ts_day) OVER (PARTITION BY pickup_zone_id ORDER BY ts_day
                          ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rows_frame_start,
        COUNT(*) OVER (PARTITION BY pickup_zone_id ORDER BY ts_day::TIMESTAMP
                       RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW) AS range_frame_size
    FROM sparse
)
SELECT
    COUNT(*) AS n_rows,
    COUNT(*) FILTER (WHERE ts_day - rows_frame_start > 6) AS rows_frame_spans_more_than_7_days
FROM cmp
""")

   n_rows  rows_frame_spans_more_than_7_days
0    8486                               3335

### Feature 3. Rolling 30-day fare volatility

In [14]:
run(f"""
SELECT
    pickup_zone_id,
    ts_day,
    avg_fare,
    STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,
    COUNT(*)              OVER w30 AS days_in_window
FROM t7_hw_taxi_daily
WHERE pickup_zone_id = {DEMO_ZONE}
WINDOW w30 AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day::TIMESTAMP
    RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
""")

    pickup_zone_id      ts_day avg_fare rolling_std_fare_30d  days_in_window
0              132  2024-02-01    62.03                 None               1
1              132  2024-02-02    65.58   2.5102290732122437               2
2              132  2024-02-03    61.30   2.2896069531690368               3
3              132  2024-02-04    64.15   1.9603486084537787               4
4              132  2024-02-05    65.96   2.0820254561364037               5
5              132  2024-02-06    64.37   1.8765011768359397               6
6              132  2024-02-07    63.81   1.7133287011239957               7
7              132  2024-02-08    63.11   1.6097687278434928               8
8              132  2024-02-09    63.21   1.5181082892131832               9
9              132  2024-02-10    63.32   1.4369891362768815              10
10             132  2024-02-11    62.62   1.4004862791837049              11
11             132  2024-02-12    61.00   1.5299960388144405              12
12             132  2024-02-13    59.09   1.8857410296138839              13
13             132  2024-02-14    64.82   1.8730208602301104              14
14             132  2024-02-15    65.37   1.8922201623640794              15
15             132  2024-02-16    66.15   1.9605533870143229              16
16             132  2024-02-17    65.16   1.9408692715924390              17
17             132  2024-02-18    60.67   2.0048584778831321              18
18             132  2024-02-19    62.76   1.9544058788238656              19
19             132  2024-02-20    60.85   1.9854928461480951              20

На першому рядку `STDDEV_SAMP` = `NULL` (вибіркове стандартне відхилення по одному значенню не визначене).

### Feature 4. Expanding cumulative trips

In [15]:
run(f"""
SELECT
    pickup_zone_id,
    ts_day,
    trip_count,
    SUM(trip_count) OVER we AS cumulative_trips,
    AVG(trip_count) OVER we AS expanding_avg_trips
FROM t7_hw_taxi_daily
WHERE pickup_zone_id = {DEMO_ZONE}
WINDOW we AS (
    PARTITION BY pickup_zone_id
    ORDER BY ts_day
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
)
ORDER BY pickup_zone_id, ts_day
LIMIT 20
""")

    pickup_zone_id      ts_day  trip_count  cumulative_trips   expanding_avg_trips
0              132  2024-02-01         312               312  312.0000000000000000
1              132  2024-02-02         294               606  303.0000000000000000
2              132  2024-02-03         267               873  291.0000000000000000
3              132  2024-02-04         412              1285  321.2500000000000000
4              132  2024-02-05         352              1637  327.4000000000000000
5              132  2024-02-06         322              1959  326.5000000000000000
6              132  2024-02-07         279              2238  319.7142857142857143
7              132  2024-02-08         326              2564  320.5000000000000000
8              132  2024-02-09         331              2895  321.6666666666666667
9              132  2024-02-10         294              3189  318.9000000000000000
10             132  2024-02-11         376              3565  324.0909090909090909
11             132  2024-02-12         368              3933  327.7500000000000000
12             132  2024-02-13         262              4195  322.6923076923076923
13             132  2024-02-14         304              4499  321.3571428571428571
14             132  2024-02-15         298              4797  319.8000000000000000
15             132  2024-02-16         343              5140  321.2500000000000000
16             132  2024-02-17         310              5450  320.5882352941176471
17             132  2024-02-18         343              5793  321.8333333333333333
18             132  2024-02-19         460              6253  329.1052631578947368
19             132  2024-02-20         386              6639  331.9500000000000000

### Combined feature view

Усі 4 window definitions (`w_pid`, `w7`, `w30`, `we`) містять `PARTITION BY pickup_zone_id`.

**Про leakage.** Усі frames закінчуються на `CURRENT ROW`, тобто rolling-ознаки включають поточний день.
Якщо target — це `trip_count` того ж дня, `rolling_avg_fare_7d` / `cumulative_trips` містили б інформацію з target-дня.
Для прогнозу «на завтра» target треба брати як `LEAD(trip_count, 1)`, або frame робити `... AND 1 PRECEDING`.
У view додано колонку `target_trips_next_day` саме для цього.

In [16]:
run("""
CREATE OR REPLACE VIEW v_t7_hw_taxi_features AS
WITH features_basic AS (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        avg_fare,
        total_distance,

        LAG(trip_count, 1)  OVER w_pid AS trips_lag_1d,
        LAG(trip_count, 7)  OVER w_pid AS trips_lag_7d,
        LAG(trip_count, 30) OVER w_pid AS trips_lag_30d,

        AVG(avg_fare) OVER w7 AS rolling_avg_fare_7d,
        STDDEV_SAMP(avg_fare) OVER w30 AS rolling_std_fare_30d,

        SUM(trip_count) OVER we AS cumulative_trips,
        AVG(trip_count) OVER we AS expanding_avg_trips,

        LEAD(trip_count, 1) OVER w_pid AS target_trips_next_day
    FROM t7_hw_taxi_daily
    WINDOW
        w_pid AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
        ),
        w7 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '6 days' PRECEDING AND CURRENT ROW
        ),
        w30 AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day::TIMESTAMP
            RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
        ),
        we AS (
            PARTITION BY pickup_zone_id
            ORDER BY ts_day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        )
)
SELECT *
FROM features_basic
WHERE trips_lag_30d IS NOT NULL;
""")

In [17]:
run(f"""
SELECT *
FROM v_t7_hw_taxi_features
WHERE pickup_zone_id = {DEMO_ZONE}
ORDER BY pickup_zone_id, ts_day
LIMIT 20
""")

,pickup_zone_id,ts_day,trip_count,avg_fare,total_distance,trips_lag_1d,trips_lag_7d,trips_lag_30d,rolling_avg_fare_7d,rolling_std_fare_30d,cumulative_trips,expanding_avg_trips,target_trips_next_day
0,132,2024-03-02,261,61.48,4153.22,285,376,312,63.2557142857142857,1.9281313984412920,10640,343.2258064516129032,356
1,132,2024-03-03,356,63.50,5582.80,261,431,294,63.0500000000000000,1.8738889735140317,10996,343.6250000000000000,395
2,132,2024-03-04,395,65.78,6534.27,356,473,267,63.6342857142857143,1.9063906138076197,11391,345.1818181818181818,301
3,132,2024-03-05,301,60.91,4530.20,395,420,412,63.3257142857142857,1.9431335340203675,11692,343.8823529411764706,298
4,132,2024-03-06,298,63.25,4747.55,301,386,352,63.5542857142857143,1.8675463034158749,11990,342.5714285714285714,273
5,132,2024-03-07,273,63.27,4249.18,298,341,322,63.3914285714285714,1.8508234886684620,12263,340.6388888888888889,273
6,132,2024-03-08,273,67.12,4495.30,273,285,279,63.6157142857142857,1.9949344183038532,12536,338.8108108108108108,257
7,132,2024-03-09,257,62.18,3955.05,273,261,326,63.7157142857142857,2.0018641886714137,12793,336.6578947368421053,371
8,132,2024-03-10,371,64.56,5897.81,257,356,331,63.8671428571428571,2.0204087727970799,13164,337.5384615384615385,414
9,132,2024-03-11,414,63.94,6528.89,371,395,294,63.6042857142857143,2.0258334172588719,13578,339.4500000000000000,309
10,132,2024-03-12,309,63.65,4951.81,414,301,376,63.9957142857142857,2.0256726993908644,13887,338.7073170731707317,314
11,132,2024-03-13,314,63.79,5013.20,309,298,368,64.0728571428571429,1.9866931167721614,14201,338.1190476190476190,312
12,132,2024-03-14,312,65.76,5091.10,314,273,262,64.4285714285714286,1.8746518450714749,14513,337.5116279069767442,326
13,132,2024-03-15,326,64.46,5224.92,312,273,304,64.0485714285714286,1.8668925561188448,14839,337.2500000000000000,352
14,132,2024-03-16,352,62.94,5677.04,326,257,298,64.1571428571428571,1.8337966708130587,15191,337.5777777777777778,379
15,132,2024-03-17,379,66.21,6265.92,352,371,343,64.3928571428571429,1.8369477745534252,15570,338.4782608695652174,401
16,132,2024-03-18,401,64.80,6543.56,379,414,310,64.5157142857142857,1.8261009590500954,15971,339.8085106382978723,354
17,132,2024-03-19,354,65.41,5672.56,401,309,343,64.7671428571428571,1.7887832183634915,16325,340.1041666666666667,321
18,132,2024-03-20,321,61.72,5008.94,354,314,460,64.4714285714285714,1.8141515543275224,16646,339.7142857142857143,323
19,132,2024-03-21,323,63.66,5112.53,321,312,386,64.1714285714285714,1.7439549451103124,16969,339.3800000000000000,334

In [18]:
run("""
SELECT
    COUNT(*) AS n_feature_rows,
    COUNT(DISTINCT pickup_zone_id) AS n_zones,
    MIN(ts_day) AS first_day,
    MAX(ts_day) AS last_day
FROM v_t7_hw_taxi_features
""")

   n_feature_rows  n_zones   first_day    last_day
0            7200      240  2024-03-02  2024-03-31

**Демонстрація тихої помилки без `PARTITION BY`.** На першому дні кожної зони `LAG` без партиції бере
`trip_count` останнього дня *попередньої* зони:

In [19]:
run("""
WITH cmp AS (
    SELECT
        pickup_zone_id,
        ts_day,
        trip_count,
        LAG(trip_count) OVER (PARTITION BY pickup_zone_id ORDER BY ts_day) AS lag_correct,
        LAG(trip_count) OVER (ORDER BY pickup_zone_id, ts_day)             AS lag_leaky
    FROM t7_hw_taxi_daily
)
SELECT *
FROM cmp
WHERE lag_correct IS DISTINCT FROM lag_leaky
ORDER BY pickup_zone_id, ts_day
LIMIT 5
""")

   pickup_zone_id      ts_day  trip_count lag_correct  lag_leaky
0               3  2024-02-01           0        None          0
1               4  2024-02-01           5        None          0
2               6  2024-02-01           0        None         26
3               7  2024-02-01           5        None          0
4               9  2024-02-01           0        None          9

## Завдання 3. JSONB event-log

Синтетичний event-log: 50 000 подій, 1 000 користувачів, 60 днів, 5 типів подій з різною схемою `payload`.
`event_ts` — `TIMESTAMPTZ` з фіксованою опорною датою (не `NOW()`), тому результати відтворювані.

In [20]:
run("""
DROP TABLE IF EXISTS t7_hw_checkouts_norm;
DROP TABLE IF EXISTS t7_hw_events;

CREATE TABLE t7_hw_events (
    event_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    event_ts    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type  TEXT NOT NULL,
    payload     JSONB NOT NULL
);

INSERT INTO t7_hw_events (user_id, event_ts, event_type, payload)
SELECT
    (n % 1000) + 1 AS user_id,
    TIMESTAMPTZ '2024-04-01 00:00:00+00'
        - ((n % 60) || ' days')::INTERVAL AS event_ts,
    CASE (n % 5)
        WHEN 0 THEN 'page_view'
        WHEN 1 THEN 'click'
        WHEN 2 THEN 'add_to_cart'
        WHEN 3 THEN 'checkout'
        ELSE        'recommendation_shown'
    END AS event_type,
    CASE (n % 5)
        WHEN 0 THEN jsonb_build_object(
            'url', '/product/' || ((n % 200) + 1),
            'referrer', (ARRAY['google','direct','email','fb'])[(n % 4) + 1],
            'device', (ARRAY['mobile','desktop','tablet'])[(n % 3) + 1]
        )
        WHEN 1 THEN jsonb_build_object(
            'element_id', 'btn_' || ((n % 50) + 1),
            'page_url', '/category/' || ((n % 20) + 1),
            'device', (ARRAY['mobile','desktop'])[(n % 2) + 1]
        )
        WHEN 2 THEN jsonb_build_object(
            'product_id', (n % 200) + 1,
            'price', ((n % 100) + 10)::NUMERIC(10, 2),
            'quantity', (n % 5) + 1,
            'tags', jsonb_build_array(
                (ARRAY['promo','new','clearance'])[(n % 3) + 1]
            )
        )
        WHEN 3 THEN jsonb_build_object(
            'order_id', 'o_' || (n + 100000),
            'total', ((n % 500) + 50)::NUMERIC(10, 2),
            'items_count', (n % 10) + 1,
            'payment_method', (ARRAY['card','paypal','crypto'])[(n % 3) + 1]
        )
        ELSE jsonb_build_object(
            'model_name', 'rec_v' || ((n % 5) + 1),
            'model_version', '1.' || (n % 10),
            'recommendations', jsonb_build_array(
                (n % 200) + 1,
                ((n + 1) % 200) + 1,
                ((n + 2) % 200) + 1
            ),
            'experiment', 'exp_' || ((n % 3) + 1)
        )
    END AS payload
FROM generate_series(1, 50000) AS n;

ANALYZE t7_hw_events;

SELECT event_type, COUNT(*) AS n_events
FROM t7_hw_events
GROUP BY event_type
ORDER BY event_type;
""")

             event_type  n_events
0           add_to_cart     10000
1              checkout     10000
2                 click     10000
3             page_view     10000
4  recommendation_shown     10000

Різні схеми payload — набір top-level ключів для кожного типу події:

In [21]:
run("""
SELECT
    event_type,
    string_agg(DISTINCT k, ', ' ORDER BY k) AS payload_keys
FROM t7_hw_events, jsonb_object_keys(payload) AS k
GROUP BY event_type
ORDER BY event_type
""")

             event_type                                            payload_keys
0           add_to_cart                       price, product_id, quantity, tags
1              checkout            items_count, order_id, payment_method, total
2                 click                            device, element_id, page_url
3             page_view                                   device, referrer, url
4  recommendation_shown  experiment, model_name, model_version, recommendations

### JSONB Query 1. Containment `@>`

In [22]:
run("""
SELECT event_id, user_id, event_ts, payload
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND payload @> jsonb_build_object('payment_method', 'card')
ORDER BY event_id
LIMIT 10
""")

   event_id  user_id                  event_ts                                                                               payload
0         3        4 2024-03-29 00:00:00+00:00   {'total': 53.0, 'order_id': 'o_100003', 'items_count': 4, 'payment_method': 'card'}
1        18       19 2024-03-14 00:00:00+00:00   {'total': 68.0, 'order_id': 'o_100018', 'items_count': 9, 'payment_method': 'card'}
2        33       34 2024-02-28 00:00:00+00:00   {'total': 83.0, 'order_id': 'o_100033', 'items_count': 4, 'payment_method': 'card'}
3        48       49 2024-02-13 00:00:00+00:00   {'total': 98.0, 'order_id': 'o_100048', 'items_count': 9, 'payment_method': 'card'}
4        63       64 2024-03-29 00:00:00+00:00  {'total': 113.0, 'order_id': 'o_100063', 'items_count': 4, 'payment_method': 'card'}
5        78       79 2024-03-14 00:00:00+00:00  {'total': 128.0, 'order_id': 'o_100078', 'items_count': 9, 'payment_method': 'card'}
6        93       94 2024-02-28 00:00:00+00:00  {'total': 143.0, 'order_id': 'o_100093', 'items_count': 4, 'payment_method': 'card'}
7       108      109 2024-02-13 00:00:00+00:00  {'total': 158.0, 'order_id': 'o_100108', 'items_count': 9, 'payment_method': 'card'}
8       123      124 2024-03-29 00:00:00+00:00  {'total': 173.0, 'order_id': 'o_100123', 'items_count': 4, 'payment_method': 'card'}
9       138      139 2024-03-14 00:00:00+00:00  {'total': 188.0, 'order_id': 'o_100138', 'items_count': 9, 'payment_method': 'card'}

### JSONB Query 2. Key existence `?` та `?|`

In [23]:
run("""
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ? 'tags'
ORDER BY event_id
LIMIT 10
""")

   event_id   event_type                                                                  payload
0         2  add_to_cart   {'tags': ['clearance'], 'price': 12.0, 'quantity': 3, 'product_id': 3}
1         7  add_to_cart         {'tags': ['new'], 'price': 17.0, 'quantity': 3, 'product_id': 8}
2        12  add_to_cart      {'tags': ['promo'], 'price': 22.0, 'quantity': 3, 'product_id': 13}
3        17  add_to_cart  {'tags': ['clearance'], 'price': 27.0, 'quantity': 3, 'product_id': 18}
4        22  add_to_cart        {'tags': ['new'], 'price': 32.0, 'quantity': 3, 'product_id': 23}
5        27  add_to_cart      {'tags': ['promo'], 'price': 37.0, 'quantity': 3, 'product_id': 28}
6        32  add_to_cart  {'tags': ['clearance'], 'price': 42.0, 'quantity': 3, 'product_id': 33}
7        37  add_to_cart        {'tags': ['new'], 'price': 47.0, 'quantity': 3, 'product_id': 38}
8        42  add_to_cart      {'tags': ['promo'], 'price': 52.0, 'quantity': 3, 'product_id': 43}
9        47  add_to_cart  {'tags': ['clearance'], 'price': 57.0, 'quantity': 3, 'product_id': 48}

In [24]:
run("""
SELECT event_id, event_type, payload
FROM t7_hw_events
WHERE payload ?| ARRAY['experiment', 'model_version']
ORDER BY event_id
LIMIT 10
""")

   event_id            event_type                                                                                                   payload
0         4  recommendation_shown     {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [5, 6, 7]}
1         9  recommendation_shown  {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [10, 11, 12]}
2        14  recommendation_shown  {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [15, 16, 17]}
3        19  recommendation_shown  {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [20, 21, 22]}
4        24  recommendation_shown  {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [25, 26, 27]}
5        29  recommendation_shown  {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [30, 31, 32]}
6        34  recommendation_shown  {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [35, 36, 37]}
7        39  recommendation_shown  {'experiment': 'exp_1', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [40, 41, 42]}
8        44  recommendation_shown  {'experiment': 'exp_3', 'model_name': 'rec_v5', 'model_version': '1.4', 'recommendations': [45, 46, 47]}
9        49  recommendation_shown  {'experiment': 'exp_2', 'model_name': 'rec_v5', 'model_version': '1.9', 'recommendations': [50, 51, 52]}

`?`, `?|`, `?&` перевіряють лише **top-level** ключі. Для їх індексації потрібен GIN з default `jsonb_ops`;
`jsonb_path_ops` (який створюємо нижче) ці оператори не підтримує, зате менший і швидший для `@>` / JSONPath.

### JSONB Query 3. JSONPath

In [25]:
run("""
SELECT
    event_id,
    jsonb_path_query(payload, '$.recommendations[*]') AS recommended_pid
FROM t7_hw_events
WHERE event_type = 'recommendation_shown'
ORDER BY event_id
LIMIT 15
""")

    event_id  recommended_pid
0          4                5
1          4                6
2          4                7
3          9               10
4          9               11
5          9               12
6         14               15
7         14               16
8         14               17
9         19               20
10        19               21
11        19               22
12        24               25
13        24               26
14        24               27

In [26]:
run("""
SELECT
    event_id,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total
FROM t7_hw_events
WHERE event_type = 'checkout'
  AND jsonb_path_exists(payload, '$.total ? (@ > 300)')
ORDER BY event_id
LIMIT 10
""")

   event_id  order_id   total
0       253  o_100253  303.00
1       258  o_100258  308.00
2       263  o_100263  313.00
3       268  o_100268  318.00
4       273  o_100273  323.00
5       278  o_100278  328.00
6       283  o_100283  333.00
7       288  o_100288  338.00
8       293  o_100293  343.00
9       298  o_100298  348.00

## Завдання 4. GIN-index demo + `EXPLAIN (ANALYZE, BUFFERS)`

Очікувана селективність (зі схеми генерації):

* `payment_method = card` — `n % 5 = 3` і `n % 3 = 0` → ~3 333 з 50 000 (≈6.7%);
* `referrer = google` — `n % 5 = 0` і `n % 4 = 0` → 2 500 (5%);
* `device = mobile` — page_view (`n % 15 = 0`, ~3 333) + click (`n % 10 = 6`, 5 000) → ~8 333 (≈16.7%).

Розмір таблиці:

In [27]:
run("""
SELECT
    pg_size_pretty(pg_relation_size('t7_hw_events')) AS heap_size,
    pg_relation_size('t7_hw_events') / current_setting('block_size')::INT AS heap_pages,
    pg_size_pretty(pg_total_relation_size('t7_hw_events')) AS total_size
""")

  heap_size  heap_pages total_size
0   8000 kB        1000    9144 kB

### Step 1. Containment query без GIN-індексу

In [28]:
run("""
DROP INDEX IF EXISTS idx_t7_events_payload_gin_pathops;
DROP INDEX IF EXISTS idx_t7_events_payload_gin_ops;
DROP INDEX IF EXISTS idx_t7_events_device_btree;

ANALYZE t7_hw_events;
""")

In [29]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
""")

Aggregate  (cost=1759.06..1759.07 rows=1 width=8) (actual time=12.534..12.535 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1750.00 rows=3624 width=0) (actual time=0.004..12.460 rows=3334 loops=1)
        Filter: (payload @> jsonb_build_object('payment_method', 'card'))
        Rows Removed by Filter: 46666
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=7
Planning Time: 0.077 ms
Execution Time: 12.542 ms

### Step 2. GIN-індекс (`jsonb_path_ops`) для containment / JSONPath workload

In [30]:
run("""
CREATE INDEX idx_t7_events_payload_gin_pathops
    ON t7_hw_events USING GIN (payload jsonb_path_ops);

ANALYZE t7_hw_events;

SELECT pg_size_pretty(pg_relation_size('idx_t7_events_payload_gin_pathops'))
       AS gin_index_size;
""")

  gin_index_size
0        1144 kB

### Step 3. Той самий containment query після GIN

In [31]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('payment_method', 'card');
""")

Aggregate  (cost=1106.54..1106.55 rows=1 width=8) (actual time=1.621..1.621 rows=1 loops=1)
  Buffers: shared hit=1004
  ->  Bitmap Heap Scan on t7_hw_events  (cost=37.62..1096.69 rows=3938 width=0) (actual time=0.193..1.557 rows=3334 loops=1)
        Recheck Cond: (payload @> jsonb_build_object('payment_method', 'card'))
        Heap Blocks: exact=1000
        Buffers: shared hit=1004
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..36.64 rows=3938 width=0) (actual time=0.135..0.135 rows=3334 loops=1)
              Index Cond: (payload @> jsonb_build_object('payment_method', 'card'))
              Buffers: shared hit=4
Planning:
  Buffers: shared hit=27
Planning Time: 0.137 ms
Execution Time: 1.632 ms

In [32]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @> jsonb_build_object('referrer', 'google');
""")

Aggregate  (cost=1064.97..1064.98 rows=1 width=8) (actual time=1.100..1.100 rows=1 loops=1)
  Buffers: shared hit=1004
  ->  Bitmap Heap Scan on t7_hw_events  (cost=24.86..1059.24 rows=2292 width=0) (actual time=0.157..1.048 rows=2500 loops=1)
        Recheck Cond: (payload @> jsonb_build_object('referrer', 'google'))
        Heap Blocks: exact=1000
        Buffers: shared hit=1004
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..24.29 rows=2292 width=0) (actual time=0.100..0.100 rows=2500 loops=1)
              Index Cond: (payload @> jsonb_build_object('referrer', 'google'))
              Buffers: shared hit=4
Planning:
  Buffers: shared hit=1
Planning Time: 0.038 ms
Execution Time: 1.107 ms

Додатково: `jsonb_path_ops` також обслуговує JSONPath-предикати `@?` / `@@`, але **не** `?` (key existence):

In [33]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload @? '$.payment_method ? (@ == "card")';
""")

Aggregate  (cost=1096.69..1096.70 rows=1 width=8) (actual time=0.888..0.888 rows=1 loops=1)
  Buffers: shared hit=1004
  ->  Bitmap Heap Scan on t7_hw_events  (cost=37.62..1086.84 rows=3938 width=0) (actual time=0.162..0.825 rows=3334 loops=1)
        Recheck Cond: (payload @? '$."payment_method"?(@ == "card")'::jsonpath)
        Heap Blocks: exact=1000
        Buffers: shared hit=1004
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_pathops  (cost=0.00..36.64 rows=3938 width=0) (actual time=0.111..0.112 rows=3334 loops=1)
              Index Cond: (payload @? '$."payment_method"?(@ == "card")'::jsonpath)
              Buffers: shared hit=4
Planning:
  Buffers: shared hit=4
Planning Time: 0.040 ms
Execution Time: 0.896 ms

In [34]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ? 'tags';
""")

Aggregate  (cost=1649.78..1649.79 rows=1 width=8) (actual time=2.772..2.772 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1625.00 rows=9912 width=0) (actual time=0.003..2.581 rows=10000 loops=1)
        Filter: (payload ? 'tags'::text)
        Rows Removed by Filter: 40000
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=2
Planning Time: 0.030 ms
Execution Time: 2.776 ms

### Порівняння `jsonb_path_ops` vs `jsonb_ops`

Для повноти створюємо також default `jsonb_ops`, порівнюємо розміри і дивимось план для `?`. Після
порівняння індекс видаляємо, щоб він не впливав на наступні кроки.

In [35]:
run("""
CREATE INDEX idx_t7_events_payload_gin_ops
    ON t7_hw_events USING GIN (payload);

ANALYZE t7_hw_events;

SELECT
    pg_size_pretty(pg_relation_size('idx_t7_events_payload_gin_pathops')) AS gin_jsonb_path_ops_size,
    pg_size_pretty(pg_relation_size('idx_t7_events_payload_gin_ops'))     AS gin_jsonb_ops_size;
""")

  gin_jsonb_path_ops_size gin_jsonb_ops_size
0                 1144 kB            1696 kB

In [36]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ? 'tags';
""")

Aggregate  (cost=1232.56..1232.57 rows=1 width=8) (actual time=1.935..1.935 rows=1 loops=1)
  Buffers: shared hit=1006
  ->  Bitmap Heap Scan on t7_hw_events  (cost=78.96..1206.96 rows=10240 width=0) (actual time=0.352..1.746 rows=10000 loops=1)
        Recheck Cond: (payload ? 'tags'::text)
        Heap Blocks: exact=1000
        Buffers: shared hit=1006
        ->  Bitmap Index Scan on idx_t7_events_payload_gin_ops  (cost=0.00..76.40 rows=10240 width=0) (actual time=0.289..0.289 rows=10000 loops=1)
              Index Cond: (payload ? 'tags'::text)
              Buffers: shared hit=6
Planning:
  Buffers: shared hit=27
Planning Time: 0.172 ms
Execution Time: 1.949 ms

In [37]:
run("""
DROP INDEX IF EXISTS idx_t7_events_payload_gin_ops;
ANALYZE t7_hw_events;
""")

### Step 4. Коли GIN не допомагає: path-specific text equality

In [38]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile';
""")

Aggregate  (cost=1750.62..1750.63 rows=1 width=8) (actual time=2.680..2.681 rows=1 loops=1)
  Buffers: shared hit=1000
  ->  Seq Scan on t7_hw_events  (cost=0.00..1750.00 rows=250 width=0) (actual time=0.005..2.521 rows=8333 loops=1)
        Filter: ((payload ->> 'device'::text) = 'mobile'::text)
        Rows Removed by Filter: 41667
        Buffers: shared hit=1000
Planning:
  Buffers: shared hit=5
Planning Time: 0.065 ms
Execution Time: 2.689 ms

Тепер expression B-tree index на `payload ->> 'device'`:

In [39]:
run("""
CREATE INDEX idx_t7_events_device_btree
    ON t7_hw_events ((payload ->> 'device'));

ANALYZE t7_hw_events;

SELECT pg_size_pretty(pg_relation_size('idx_t7_events_device_btree')) AS btree_index_size;
""")

  btree_index_size
0           360 kB

In [40]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT COUNT(*)
FROM t7_hw_events
WHERE payload ->> 'device' = 'mobile';
""")

Aggregate  (cost=1242.55..1242.56 rows=1 width=8) (actual time=1.316..1.317 rows=1 loops=1)
  Buffers: shared hit=1000 read=9
  ->  Bitmap Heap Scan on t7_hw_events  (cost=96.82..1221.73 rows=8327 width=0) (actual time=0.184..1.115 rows=8333 loops=1)
        Recheck Cond: ((payload ->> 'device'::text) = 'mobile'::text)
        Heap Blocks: exact=1000
        Buffers: shared hit=1000 read=9
        ->  Bitmap Index Scan on idx_t7_events_device_btree  (cost=0.00..94.74 rows=8327 width=0) (actual time=0.125..0.125 rows=8333 loops=1)
              Index Cond: ((payload ->> 'device'::text) = 'mobile'::text)
              Buffers: shared read=9
Planning:
  Buffers: shared hit=18 read=1
Planning Time: 0.105 ms
Execution Time: 1.327 ms

### Write-side cost індексів

Read-пришвидшення не безкоштовне: кожен `INSERT` має оновити GIN (по entry на кожну пару path/value у payload).
Вимірюємо час вставки 50 000 подій у копію таблиці без індексів і з GIN `jsonb_path_ops`. Тут `fastupdate`
залишено за замовчуванням (`on`) — PostgreSQL складає нові entries у pending list і зливає їх в індекс пакетно.

In [41]:
import time

def timed_insert(with_gin):
    run("""
    DROP TABLE IF EXISTS t7_hw_events_write_test;
    CREATE TABLE t7_hw_events_write_test (LIKE t7_hw_events INCLUDING DEFAULTS);
    """)
    if with_gin:
        run("CREATE INDEX ON t7_hw_events_write_test USING GIN (payload jsonb_path_ops);")
    start = time.perf_counter()
    run("""
    INSERT INTO t7_hw_events_write_test
    SELECT * FROM t7_hw_events;
    """)
    elapsed = time.perf_counter() - start
    size = run("SELECT pg_size_pretty(pg_total_relation_size('t7_hw_events_write_test')) AS s").iloc[0, 0]
    return elapsed, size

results = []
for with_gin in (False, True, False, True):
    elapsed, size = timed_insert(with_gin)
    results.append({'gin_index': with_gin, 'insert_50k_sec': round(elapsed, 3), 'total_size': size})
run("DROP TABLE IF EXISTS t7_hw_events_write_test;")
pd.DataFrame(results)

   gin_index  insert_50k_sec total_size
0      False           0.060    8032 kB
1       True           0.175      12 MB
2      False           0.053    8032 kB
3       True           0.168      12 MB

## Завдання 5. JSONB vs normalized

### Step 1. Нормалізована таблиця для checkout-подій

In [42]:
run("""
DROP TABLE IF EXISTS t7_hw_checkouts_norm;

CREATE TABLE t7_hw_checkouts_norm (
    event_id        INTEGER PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    event_ts        TIMESTAMPTZ NOT NULL,
    order_id        TEXT NOT NULL,
    total           NUMERIC(10, 2) NOT NULL,
    items_count     INTEGER NOT NULL CHECK (items_count > 0),
    payment_method  TEXT NOT NULL CHECK (payment_method IN ('card', 'paypal', 'crypto'))
);

INSERT INTO t7_hw_checkouts_norm (
    event_id,
    user_id,
    event_ts,
    order_id,
    total,
    items_count,
    payment_method
)
SELECT
    event_id,
    user_id,
    event_ts,
    payload ->> 'order_id' AS order_id,
    (payload ->> 'total')::NUMERIC(10, 2) AS total,
    (payload ->> 'items_count')::INTEGER AS items_count,
    payload ->> 'payment_method' AS payment_method
FROM t7_hw_events
WHERE event_type = 'checkout';

CREATE INDEX idx_t7_checkouts_norm_pm
    ON t7_hw_checkouts_norm (payment_method);

ANALYZE t7_hw_checkouts_norm;

SELECT COUNT(*) AS n_checkouts
FROM t7_hw_checkouts_norm;
""")

   n_checkouts
0        10000

In [43]:
run("""
SELECT
    pg_size_pretty(pg_relation_size('t7_hw_events'))         AS events_heap_all_types,
    pg_size_pretty(pg_relation_size('t7_hw_checkouts_norm')) AS checkouts_norm_heap
""")

  events_heap_all_types checkouts_norm_heap
0               8000 kB              752 kB

### Step 2. Один запит двома способами

JSONB-версія:

In [44]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payload ->> 'payment_method' AS payment_method,
    AVG((payload ->> 'total')::NUMERIC) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_events
WHERE event_type = 'checkout'
GROUP BY payload ->> 'payment_method'
ORDER BY avg_total DESC
LIMIT 3;
""")

Limit  (cost=1959.95..1959.95 rows=3 width=72) (actual time=3.632..3.633 rows=3 loops=1)
  Buffers: shared hit=1000
  ->  Sort  (cost=1959.95..1974.03 rows=5635 width=72) (actual time=3.632..3.632 rows=3 loops=1)
        Sort Key: (avg(((payload ->> 'total'::text))::numeric)) DESC
        Sort Method: quicksort  Memory: 25kB
        Buffers: shared hit=1000
        ->  HashAggregate  (cost=1802.59..1887.11 rows=5635 width=72) (actual time=3.615..3.629 rows=3 loops=1)
              Group Key: (payload ->> 'payment_method'::text)
              Batches: 1  Memory Usage: 217kB
              Buffers: shared hit=1000
              ->  Seq Scan on t7_hw_events  (cost=0.00..1650.37 rows=10148 width=131) (actual time=0.004..2.239 rows=10000 loops=1)
                    Filter: (event_type = 'checkout'::text)
                    Rows Removed by Filter: 40000
                    Buffers: shared hit=1000
Planning:
  Buffers: shared hit=16
Planning Time: 0.061 ms
Execution Time: 3.647 ms

Normalized-версія:

In [45]:
explain("""
EXPLAIN (ANALYZE, BUFFERS)
SELECT
    payment_method,
    AVG(total) AS avg_total,
    COUNT(*) AS n
FROM t7_hw_checkouts_norm
GROUP BY payment_method
ORDER BY avg_total DESC
LIMIT 3;
""")

Limit  (cost=269.06..269.07 rows=3 width=46) (actual time=1.023..1.024 rows=3 loops=1)
  Buffers: shared hit=94
  ->  Sort  (cost=269.06..269.07 rows=3 width=46) (actual time=1.023..1.023 rows=3 loops=1)
        Sort Key: (avg(total)) DESC
        Sort Method: quicksort  Memory: 25kB
        Buffers: shared hit=94
        ->  HashAggregate  (cost=269.00..269.04 rows=3 width=46) (actual time=1.020..1.021 rows=3 loops=1)
              Group Key: payment_method
              Batches: 1  Memory Usage: 24kB
              Buffers: shared hit=94
              ->  Seq Scan on t7_hw_checkouts_norm  (cost=0.00..194.00 rows=10000 width=11) (actual time=0.003..0.307 rows=10000 loops=1)
                    Buffers: shared hit=94
Planning:
  Buffers: shared hit=34
Planning Time: 0.138 ms
Execution Time: 1.032 ms

Перевірка, що обидві версії повертають однаковий результат:

In [46]:
run("""
SELECT 'jsonb' AS source, payload ->> 'payment_method' AS payment_method,
       ROUND(AVG((payload ->> 'total')::NUMERIC), 2) AS avg_total, COUNT(*) AS n
FROM t7_hw_events
WHERE event_type = 'checkout'
GROUP BY payload ->> 'payment_method'
UNION ALL
SELECT 'normalized', payment_method, ROUND(AVG(total), 2), COUNT(*)
FROM t7_hw_checkouts_norm
GROUP BY payment_method
ORDER BY payment_method, source
""")

       source payment_method avg_total     n
0       jsonb           card    300.50  3334
1  normalized           card    300.50  3334
2       jsonb         crypto    300.48  3333
3  normalized         crypto    300.48  3333
4       jsonb         paypal    300.52  3333
5  normalized         paypal    300.52  3333

### Step 3. Bonus: MongoDB-equivalent (pseudocode)

```javascript
// MongoDB equivalent: avg total checkout per payment_method, top-3
// Pseudocode — не виконується у PostgreSQL

db.events.aggregate([
  {$match: {event_type: "checkout"}},
  {$group: {
    _id: "$payload.payment_method",
    avg_total: {$avg: {$toDouble: "$payload.total"}},
    n: {$sum: 1}
  }},
  {$sort: {avg_total: -1}},
  {$limit: 3}
]);

// Аналог GIN/expression index для $match + path-equality:
db.events.createIndex({event_type: 1, "payload.payment_method": 1});
```

**Коментар:**

* **PostgreSQL JSONB** зручний, коли поруч із напівструктурованими даними потрібні SQL, `JOIN` з нормалізованими
  таблицями (users, orders), ACID-транзакції та одна система для OLTP і feature engineering. Ми щойно зробили
  `INSERT ... SELECT payload ->> ...` з JSONB у typed-таблицю однією транзакцією — у PostgreSQL це тривіально.
* **MongoDB aggregation pipeline** природний для document-first workloads: документи з глибокою вкладеністю,
  схема змінюється часто, горизонтальне шардування з коробки. Pipeline `$match → $group → $sort → $limit`
  відповідає `WHERE → GROUP BY → ORDER BY → LIMIT`, але `$lookup` (join) там дорожчий і менш зручний.
* **High-volume raw clickstream** (мільярди подій, append-only) часто краще тримати в document store
  або data lake (Parquet на S3 + Spark/DuckDB/Trino): дешеве зберігання, колонкове читання, без write-amplification від GIN.
* **Curated ML features** (як `v_t7_hw_taxi_features` чи `t7_hw_checkouts_norm`) зручніше тримати у typed SQL-таблицях:
  явні типи, `CHECK`-constraints, B-tree індекси, стабільний контракт для training/serving.

## Reflection

_Цифри взяті з мого запуску. При повторному Run All мілісекунди трохи відрізнятимуться, але оператори плану ті самі._

**1. До і після GIN.** Без індексу запит `@> {"payment_method": "card"}` виконувався через `Seq Scan` (cost 0.00..1750.00, `Rows Removed by Filter: 46666`, прочитано всі 1000 сторінок) за 12.5 ms. З `jsonb_path_ops` я отримала `Bitmap Index Scan` + `Bitmap Heap Scan` за 1.63 ms. Цікаво, що `Heap Blocks: exact=1000` не змінився: виграш дав CPU, бо перевіряється 3 334 payload-и замість 50 000.

**2. `->> 'device'`.** Вираз `payload ->> 'device' = 'mobile'` не є оператором GIN opclass, тому план лишився `Seq Scan` (2.69 ms) з хибною оцінкою `rows=250` замість 8 333. Expression B-tree менший (360 kB проти 1 144 kB), має статистику виразу (`rows=8327`) і дав `Bitmap Index Scan` за 1.33 ms.

**3. Trade-off.** Читання `@>` прискорилося приблизно у 8 разів. Але вставка 50k рядків із GIN тривала ~0.17 s проти ~0.06 s без нього, а розмір таблиці зріс з 8 MB до 12 MB. `jsonb_ops` більший (1 696 kB), зате підтримує `?`.

**4. JSONB чи normalized.** JSONB-агрегат по checkout прочитав 1000 сторінок за 3.65 ms і очікував 5 635 груп замість 3. Normalized-версія прочитала 94 сторінки за 1.03 ms з точною оцінкою. JSONB я обрала б для raw event-log зі схемою, що змінюється, а typed-таблиці — для curated features і полів, які часто фільтрують та агрегують.

**5. `refund`.** У JSONB DDL не потрібен: достатньо `INSERT` з `event_type = 'refund'`, і GIN автоматично покриє нові ключі. Я додала б лише `CHECK` на обов'язкові ключі і оновила б consumers. У normalized-підході потрібна міграція: нова таблиця з типами, `CHECK` і FK на `order_id`, індекси, backfill через `INSERT ... SELECT` та оновлення запитів з `JOIN`.